---
# tasks file for bigip-do-network
# - name: Get Route Domain VLANs from vlans variable
#   set_fact:
#     rd_vlans: "{{ (rd_vlans | default ([]) ) + [ vlan.name ] }}"
#   loop: "{{ vlans }}"
#   loop_control:
#     loop_var: vlan
#     label: "{{ vlan.name }}"
#   when: vlan.rd is defined and vlan.rd == routeDomain.id

- name: Get Route Domain VLANs from vlans variable
  set_fact: 
    rd_vlans: "{{ vlans | selectattr('rd', 'defined') | selectattr('rd', 'equalto', routeDomain.id) | map(attribute='name') }}"

- name: Populate route Domains
  set_fact:
    tmp_route_domain: 
      class: 'RouteDomain'
      id: "{{ routeDomain.id }}"
      strict: true
#      routingProtocols:
#          - 'RIP'
      vlans: "{{ rd_vlans | default(omit) }}"

- name: appending Network configuration
  set_fact:
    do_data:  "{{ do_data |combine( { routeDomain.name : tmp_route_domain } ) }}"
  
